"""Module for components."""

from .base import Component

# This set is taken from FrooxEngine.GenericTypesAttribute.enginePrimitives.
ENGINE_PRIMITIVES: set[str] = set([
    "bool",
    "byte",
    "ushort",
    "uint",
    "ulong",
    "sbyte",
    "short",
    "int",
    "long",
    "float",
    "double",
    "Decimal",
    "char",
    "string",
    "Uri",
    "bool2",
    "byte2",
    "ushort2",
    "uint2",
    "ulong2",
    "sbyte2",
    "short2",
    "int2",
    "long2",
    "float2",
    "double2",
    "bool3",
    "byte3",
    "ushort3",
    "uint3",
    "ulong3",
    "sbyte3",
    "short3",
    "int3",
    "long3",
    "float3",
    "double3",
    "bool4",
    "byte4",
    "ushort4",
    "uint4",
    "ulong4",
    "sbyte4",
    "short4",
    "int4",
    "long4",
    "float4",
    "double4",
    "float2x2",
    "double2x2",
    "float3x3",
    "double3x3",
    "float4x4",
    "double4x4",
    "floatQ",
    "doubleQ",
    "DateTime",
    "TimeSpan",
    "color",
    "colorX",
    "color32",
])

NAMES: set[str] = set()

for primitive in ENGINE_PRIMITIVES:
    NAMES.add(f"[FrooxEngine]FrooxEngine.ValueField<{primitive}>")
