"""Module for components."""

from .base import Component

# This set is taken from FrooxEngine.GenericTypesAttribute.enginePrimitives.
ENGINE_PRIMITIVES: set[str] = set([
    "bool",
    "byte",
    "ushort",
    "uint",
    "ulong",
    "sbyte",
    "short",
    "int",
    "long",
    "float",
    "double",
    "char",
    "string",
    "Uri",
    "bool2",
    "byte2",
    "ushort2",
    "uint2",
    "ulong2",
    "sbyte2",
    "short2",
    "int2",
    "long2",
    "float2",
    "double2",
    "bool3",
    "byte3",
    "ushort3",
    "uint3",
    "ulong3",
    "sbyte3",
    "short3",
    "int3",
    "long3",
    "float3",
    "double3",
    "bool4",
    "byte4",
    "ushort4",
    "uint4",
    "ulong4",
    "sbyte4",
    "short4",
    "int4",
    "long4",
    "float4",
    "double4",
    "float2x2",
    "double2x2",
    "float3x3",
    "double3x3",
    "float4x4",
    "double4x4",
    "floatQ",
    "doubleQ",
    "DateTime",
    "TimeSpan",
    "color",
    "colorX",
])

NAMES: set[str] = set()
NAME_TO_CLASS: dict[str, type[Component]] = {}

for primitive in ENGINE_PRIMITIVES:
    NAMES.add(f"[FrooxEngine]FrooxEngine.ValueField<{primitive}>")

# Import valuefields after defining NAME_TO_CLASS to avoid circular imports
from .valuefields import components as valuefields  # pylint: disable=wrong-import-position


# Map primitive type names to their corresponding component classes.
# Note: DateTime and TimeSpan are not yet implemented.
_PRIMITIVE_TO_CLASS: dict[str, type[Component]] = {
    "DateTime": valuefields.DateTime,
    "TimeSpan": valuefields.TimeSpan,
    "bool": valuefields.Bool,
    "byte": valuefields.Byte,
    "ushort": valuefields.UShort,
    "uint": valuefields.UInt,
    "ulong": valuefields.ULong,
    "sbyte": valuefields.SByte,
    "short": valuefields.Short,
    "int": valuefields.Int,
    "long": valuefields.Long,
    "float": valuefields.Float,
    "double": valuefields.Double,
    "char": valuefields.Char,
    "string": valuefields.String,
    "Uri": valuefields.Uri,
    "color": valuefields.Color,
    "colorX": valuefields.ColorX,
    "float2": valuefields.Float2,
    "double2": valuefields.Double2,
    "byte2": valuefields.Byte2,
    "ushort2": valuefields.UShort2,
    "uint2": valuefields.UInt2,
    "ulong2": valuefields.ULong2,
    "sbyte2": valuefields.SByte2,
    "short2": valuefields.Short2,
    "int2": valuefields.Int2,
    "long2": valuefields.Long2,
    "bool2": valuefields.Bool2,
    "float3": valuefields.Float3,
    "double3": valuefields.Double3,
    "byte3": valuefields.Byte3,
    "ushort3": valuefields.UShort3,
    "uint3": valuefields.UInt3,
    "ulong3": valuefields.ULong3,
    "sbyte3": valuefields.SByte3,
    "short3": valuefields.Short3,
    "int3": valuefields.Int3,
    "long3": valuefields.Long3,
    "bool3": valuefields.Bool3,
    "float4": valuefields.Float4,
    "double4": valuefields.Double4,
    "byte4": valuefields.Byte4,
    "ushort4": valuefields.UShort4,
    "uint4": valuefields.UInt4,
    "ulong4": valuefields.ULong4,
    "sbyte4": valuefields.SByte4,
    "short4": valuefields.Short4,
    "int4": valuefields.Int4,
    "long4": valuefields.Long4,
    "bool4": valuefields.Bool4,
    "floatQ": valuefields.FloatQ,
    "doubleQ": valuefields.DoubleQ,
    "float2x2": valuefields.Float2x2,
    "double2x2": valuefields.Double2x2,
    "float3x3": valuefields.Float3x3,
    "double3x3": valuefields.Double3x3,
    "float4x4": valuefields.Float4x4,
    "double4x4": valuefields.Double4x4,
}

# Populate NAME_TO_CLASS with full type names
for primitive, cls in _PRIMITIVE_TO_CLASS.items():
    NAME_TO_CLASS[f"[FrooxEngine]FrooxEngine.ValueField<{primitive}>"] = cls
